DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE BRAND (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);
DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE DOUBLE,
    CURR VARCHAR(3),

    FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);


