DROP TABLE IF EXISTS PRICES;
DROP TABLE IF EXISTS BRAND;
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE BRAND (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);

CREATE TABLE PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255)
);
DROP TABLE IF EXISTS PRICES;
CREATE TABLE PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE_AMOUNT DOUBLE NOT NULL,
    CURR VARCHAR(3) NOT NULL,
    FOREIGN KEY (BRAND_ID) REFERENCES BRAND (ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);


